apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.endpointName }}
  namespace: {{ .Values.endpointName }}
spec:
  selector:
    istio: istio-ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{- if .Values.domainName }}
    - {{ .Values.domainName }}
    {{- else }}
    - "*"
    {{- end }}
  {{- if and .Values.tlsCert .Values.tlsKey }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE 
      credentialName: {{ .Values.endpointName }}-tls  
    hosts:
    {{- if .Values.domainName }}
    - {{ .Values.domainName }}
    {{- else }}
    - "*"
    {{- end }}
  {{- end }}
