{{- if and .Values.tlsCert .Values.tlsKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.endpointName }}-tls
  namespace: {{ .Values.endpointName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tlsCert }}
  tls.key: {{ .Values.tlsKey }}
{{- end }}
