apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.endpointName }}
  namespace: {{ .Values.endpointName }}
  labels:
    endpoint: {{ .Values.endpointName }}
spec:
  ports:
  - port: {{ .Values.port }}
    name: http
  selector:
    endpoint: {{ .Values.endpointName }}